- name: Asegurarse de que Certbot y plugin de Nginx están instalados
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Obtener certificado SSL de Let's Encrypt para el dominio
  community.general.certbot:
    domains:
      - ["{{ domain_name }}"]
    authenticator: nginx
    installer: nginx
    email: "{{ ssl_email }}"
    agree_tos: true
    redirect: true
    register_unsafely_without_email: false
    keep_until_expiring: true
    force: false
  notify: Recargar Nginx
  when: domain_name is defined and ssl_email is defined


- name: Verificar si certbot está instalado
  stat:
    path: /usr/bin/certbot
  register: certbot_installed

- name: Mostrar certificados SSL instalados por Certbot
  command: certbot certificates
  register: certbot_certificates
  changed_when: false
  when: certbot_installed.stat.exists

- name: Salida de certificados instalados
  debug:
    var: certbot_certificates.stdout_lines
  when: certbot_installed.stat.exists

