---
- name: Update all packages
  yum:
    name: "*"
    state: latest

- name: Install required packages
  yum:
    name:
      - httpd
      - php
      - php-mysql
      - mariadb-server
      - wget
    state: present

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Set permissions for WordPress
  file:
    path: /var/www/html/wordpress
    owner: apache
    group: apache
    recurse: yes

- name: Configure wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: Restart Apache
  service:
    name: httpd
    state: restarted
