# Asegura que la variable del dominio esté definida
- name: Verificar que la variable 'domain_name' está definida
  assert:
    that:
      - domain_name is defined
      - domain_name | length > 0
    fail_msg: >
      XXX ERROR XXX La variable 'domain_name' no está definida o está vacía.
      Asegúrate de establecerla en group_vars/all.yml (ej. domain_name: www.midominio.com).

# =========================
# Soporte para EFS (NFS)
# =========================

# Instala el cliente NFS necesario para montar EFS
- name: Instalar soporte para NFS (requerido por EFS)
  apt:
    name: nfs-common
    state: present
    update_cache: true

# Asegura que exista el directorio de montaje para EFS
- name: Asegurar que el punto de montaje EFS existe
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

# Monta el EFS en /var/www/html (donde se alojará WordPress)
- name: Montar EFS en /var/www/html
  mount:
    path: /var/www/html
    src: "{{ efs_id }}.efs.{{ aws_region }}.amazonaws.com:/"
    fstype: nfs4
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
    state: mounted

# =========================
# Nodo líder (solo 1 instancia hace instalación completa)
# =========================

# Define si esta instancia es el nodo líder (la que se encargará de instalar WordPress)
- name: Definir si soy el nodo líder
  set_fact:
    is_leader: "{{ inventory_hostname == groups['tag_wordpress_asg_instance'] | sort | first }}"

# =========================
# Instalación de WordPress
# =========================

- name: Obtener claves SALT únicas
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  register: wp_salts_raw
  when: is_leader

- name: Guardar salts en variable
  set_fact:
    wp_salts: "{{ wp_salts_raw.content }}"
  when: is_leader

# Instala utilidades necesarias para el proceso de descarga/descompresión
- name: Instalar dependencias necesarias
  apt:
    name:
      - curl
      - unzip
      - php-mysql
      - php-curl
    state: present
    update_cache: true

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
  when: is_leader

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes
  when: is_leader

# Elimina página de bienvenida de Nginx si existe
- name: Eliminar archivo de bienvenida de Nginx si existe
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
  ignore_errors: true
  when: is_leader

# Copia archivos de WordPress a /var/www/html
- name: Copiar WordPress a /var/www/html (sobrescribiendo)
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes
  when: is_leader

# Asegura permisos correctos en todo el directorio
- name: Establecer permisos en /var/www/html
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
  when: is_leader

# Genera el archivo wp-config.php a partir de plantilla
- name: Plantilla de wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
  when: is_leader
  notify: Recargar Nginx

# =========================
# Instalación de WP-CLI
# =========================

- name: Descargar WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp-cli.phar
    mode: '0755'

- name: Mover WP-CLI a /usr/local/bin/wp
  copy:
    src: /usr/local/bin/wp-cli.phar
    dest: /usr/local/bin/wp
    remote_src: yes
    mode: '0755'
