---
- name: Verificar que la variable 'domain_name' está definida
  assert:
    that:
      - domain_name is defined
      - domain_name | length > 0
    fail_msg: >
      X Error X La variable 'domain_name' no está definida o está vacía.
      Asegurarse de establecerla en group_vars/all.yml (ej. domain_name: www.midominio.com).

# -----------------------------
# SOPORTE EFS: NFS y montaje
# -----------------------------

- name: Instalar soporte para NFS (requerido por EFS)
  apt:
    name: nfs-common
    state: present

- name: Asegurar punto de montaje EFS
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Montar EFS en /var/www/html
  mount:
    path: /var/www/html
    src: "{{ efs_id }}.efs.{{ aws_region }}.amazonaws.com:/"
    fstype: nfs4
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
    state: mounted

# -----------------------------
# DESIGNAR LÍDER PARA INSTALACIÓN
# -----------------------------

- name: Definir si soy el nodo líder
  set_fact:
    is_leader: "{{ inventory_hostname == groups['web'][0] }}"

# -----------------------------
# INSTALACIÓN WORDPRESS (solo líder)
# -----------------------------

- name: Obtener claves SALT únicas
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  register: wp_salts_raw
  when: is_leader

- name: Guardar salts en variable
  set_fact:
    wp_salts: "{{ wp_salts_raw.content }}"
  when: is_leader

- name: Instalar dependencias necesarias
  apt:
    name:
      - curl
      - unzip
      - php-mysql
      - php-curl
    state: present

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
  when: is_leader

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes
  when: is_leader

- name: Eliminar archivo de bienvenida de Nginx si existe
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
  ignore_errors: true
  when: is_leader

- name: Copiar WordPress a /var/www/html (sobrescribiendo)
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes
  when: is_leader

- name: Establecer permisos en /var/www/html
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
  when: is_leader

- name: Plantilla de wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Recargar Nginx
  when: is_leader

# -----------------------------
# WP-CLI OPCIONAL (INSTALAR EN TODOS)
# -----------------------------

- name: Descargar WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp-cli.phar
    mode: '0755'

- name: Mover WP-CLI a /usr/local/bin/wp
  copy:
    src: /usr/local/bin/wp-cli.phar
    dest: /usr/local/bin/wp
    remote_src: yes
    mode: '0755'
