---
- name: Obtener claves SALT únicas
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  register: wp_salts_raw

- name: Guardar salts en variable
  set_fact:
    wp_salts: "{{ wp_salts_raw.content }}"

- name: Instalar dependencias necesarias
  apt:
    name:
      - curl
      - unzip
      - php-mysql
      - php-curl
    state: present

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Eliminar archivo de bienvenida de Nginx si existe
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
  ignore_errors: true

- name: Copiar WordPress a /var/www/html (sobrescribiendo)
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes

- name: Establecer permisos en /var/www/html
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes

- name: Plantilla de wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Recargar Nginx

# Instalar WP-CLI
- name: Descargar WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp-cli.phar
    mode: '0755'

- name: Mover WP-CLI a /usr/local/bin/wp
  copy:
    src: /usr/local/bin/wp-cli.phar
    dest: /usr/local/bin/wp
    remote_src: yes
    mode: '0755'

# Ejecutar instalación de WordPress si aún no se ha hecho
- name: Verificar si WordPress ya está instalado
  command: wp core is-installed --allow-root
  args:
    chdir: /var/www/html
  register: wp_installed
  ignore_errors: true
  changed_when: false

- name: Instalar WordPress si no está instalado
  command: >
    wp core install
    --url=https://{{ domain_name }}
    --title="Mi Sitio WordPress"
    --admin_user=admin
    --admin_password=admin12345
    --admin_email=admin@{{ domain_name }}
    --allow-root
  args:
    chdir: /var/www/html
  when: wp_installed.rc != 0

- name: Forzar HTTPS en siteurl
  command: wp option update siteurl https://{{ domain_name }} --allow-root
  args:
    chdir: /var/www/html
  when: wp_installed.rc == 0

- name: Forzar HTTPS en home
  command: wp option update home https://{{ domain_name }} --allow-root
  args:
    chdir: /var/www/html
  when: wp_installed.rc == 0
