---
- name: Leer outputs de Terraform
  slurp:
    src: /home/dma3470/ProFiCurs/terraform_output.json
  register: terraform_output_json

- name: Establecer fact de Terraform
  set_fact:
    terraform: "{{ terraform_output_json.content | b64decode | from_json }}"