---
- name: Instalar PHP y módulos requeridos
  apt:
    name:
      - php
      - php-fpm
      - php-mysql
      - php-curl
      - php-xml
      - php-mbstring
    state: present
    update_cache: true

- name: Asegurar que PHP-FPM está iniciado y habilitado
  service:
    name: php{{ php_version }}-fpm
    state: started
    enabled: true
