- name: Instalar PHP y módulos requeridos
  apt:
    name:
      - php8.1
      - php8.1-cli
      - php8.1-fpm
      - php8.1-mysql
      - php-mbstring
      - php-curl
      - php-xml
    state: present
