---
- name: Añadir repositorio de PHP
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Instalar PHP y extensiones necesarias
  apt:
    name: "{{ php_extensions }}"
    state: present

- name: Modificar php.ini para ajustar configuraciones de PHP
  lineinfile:
    path: "/etc/php/{{ php_ver }}/fpm/php.ini"
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    state: present
  loop:
    - { key: "memory_limit", value: "1024M" }
    - { key: "max_input_vars", value: "9999" }
    - { key: "max_execution_time", value: "600" }
    - { key: "upload_max_filesize", value: "512M" }
    - { key: "post_max_size", value: "256M" }
  notify: Reiniciar PHP-FPM

- name: Configurar pool de PHP-FPM
  template:
    src: templates/php_fpm_pool.conf.j2
    dest: /etc/php/{{ php_ver }}/fpm/pool.d/www.conf
  notify: Reiniciar PHP-FPM

- name: Asegurar la propiedad del directorio del socket de PHP-FPM
  file:
    path: /run/php/
    owner: "{{ php_fpm_user }}"
    group: "{{ php_fpm_user }}"
    recurse: yes

- name: Asegurar la propiedad del socket de PHP-FPM a www-data
  file:
    path: /run/php/php{{ php_ver }}-fpm.sock
    owner: "{{ php_fpm_user }}"
    group: "{{ php_fpm_user }}"
  become: true