---
- hosts: moodle_instance
  become: true
  vars:
    moodle_version: "4.2"
    moodle_directory: /var/www/html/moodle
    moodle_datadir: /var/moodledata
    nginx_server_name: "{{ ansible_default_ipv4.address }}"
    php_fpm_user: nginx
    database_host: "{{ terraform_rds_endpoint.output.value | default('your_rds_endpoint') }}" # Reemplaza 'your_rds_endpoint' y considera usar terraform_output
    database_name: moodle_db
    database_user: admin
    database_password: "Pirineus123$"

  roles:
    - role: common
    - role: nginx
    - role: php
    - role: database_client
    - role: moodle
    - role: configure_nginx