---
- name: Crear directorio para Moodle
  file:
    path: "{{ moodle_directory }}"
    state: directory
    owner: "{{ php_fpm_user }}"
    group: "{{ php_fpm_user }}"
    mode: '0755'
    recurse: yes

- name: Crear directorio para los datos de Moodle
  file:
    path: "{{ moodle_datadir }}"
    state: directory
    owner: "{{ php_fpm_user }}"
    group: "{{ php_fpm_user }}"
    mode: '0777'
    recurse: yes

- name: Descargar Moodle
  get_url:
    url: https://download.moodle.org/download.php/direct/stable{{ moodle_version | replace('.', '') }}/moodle-{{ moodle_version }}.zip
    dest: /tmp/moodle-{{ moodle_version }}.zip
    validate_certs: no

- name: Descomprimir Moodle
  unarchive:
    src: /tmp/moodle-{{ moodle_version }}.zip
    dest: /var/www/html/
    owner: "{{ php_fpm_user }}"
    group: "{{ php_fpm_user }}"
    creates: "{{ moodle_directory }}/index.php"
    remote_src: yes

- name: Copiar archivo de configuración de ejemplo
  copy:
    src: "{{ moodle_directory }}/config-dist.php"
    dest: "{{ moodle_directory }}/config.php"
    owner: "{{ php_fpm_user }}"
    group: "{{ php_fpm_user }}"
    mode: '0644'

- name: Configurar archivo config.php
  lineinfile:
    path: "{{ moodle_directory }}/config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "\$CFG->dbtype    = 'mysqli';", line: "\$CFG->dbtype    = 'mysqli';" }
    - { regexp: "\$CFG->dblibrary = 'native';", line: "\$CFG->dblibrary = 'native';" }
    - { regexp: "\$CFG->dbhost    = 'localhost';", line: "\$CFG->dbhost    = '{{ database_host }}';" }
    - { regexp: "\$CFG->dbname    = 'moodle';", line: "\$CFG->dbname    = '{{ database_name }}';" }
    - { regexp: "\$CFG->dbuser    = 'root';", line: "\$CFG->dbuser    = '{{ database_user }}';" }
    - { regexp: "\$CFG->dbpass    = '';", line: "\$CFG->dbpass    = '{{ database_password | quote }}';" }
    - { regexp: "\$CFG->wwwroot   = 'http:\/\/www.example.com\/moodle';", line: "\$CFG->wwwroot   = 'http:\/\/{{ nginx_server_name }}';" }
    - { regexp: "\$CFG->dataroot  = '\/var\/moodledata';", line: "\$CFG->dataroot  = '{{ moodle_datadir }}';" }
  notify:
    - restart php-fpm