---
- name: Configurar playbook con los outputs de terraform
  hosts: localhost
  roles:
    - terraform_setup

- name: Configurar servidor web para Moodle
  hosts: moodle_instance
  become: true
  vars:
    nginx_server_name: "chirterfir.cat"
    php_fpm_user: www-data
    database_host: "{{ terraform.rds_endpoint.value }}"
    database_name: moodle_db
    database_user: admin
    database_password: "Pirineus123$"
  roles:
    - common
    - webserver
    - php
    - moodle