---
- name: Configurar playbook con los outputs de terraform
  hosts: localhost
  roles:
    - terraform_setup

- name: Configurar servidor web para Moodle
  hosts: moodle_instance
  become: true
  vars:
    nginx_server_name: "chirterfir.cat"
    php_fpm_user: www-data
    database_host: "rds-instance.crwuks62myjn.us-east-1.rds.amazonaws.com:3306"
    database_name: moodle_db
    database_user: admin
    database_password: "Pirineus123$"
    database_root_pw: "Pirineus123$"
  roles:
    - common
    - php
    - bd
    - webserver
    - moodle